name: panvimdoc

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    paths:
      - "README.md"
      - "**.yml"

jobs:
  docs:
    runs-on: ubuntu-latest
    name: pandoc to vimdoc
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: possession
          version: "Neovim >= 0.8.0"
          demojify: true
          treesitter: true
      - uses: stefanzweifel/git-auto-commit-action@v4
        if: startsWith(github.ref, 'refs/heads/')
        with:
          commit_message: "docs: auto generate vim documentation"
          branch: ${{ github.ref_name }}
